import { Teacher } from './types';

export const OFFICIAL_CU_FACULTY_LIST: Teacher[] = [
  {
    id: 'cu-6220',
    userId: '',
    name: 'Dr. Sandeep Singh Kang',
    empId: '6220',
    email: 'ad1.cse@cumail.in',
    phone: '97819 26200',
    department: 'Computer Science & Engineering',
    designation: 'Professor / Associate Director',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '312',
    cabinNumber: 'Cabin 312',
    subjects: ['Computer Science', 'Advanced Computing'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-8657',
    userId: '',
    name: 'Er. Gagandeep Singh',
    empId: '8657',
    email: 'gagandeep.e8657@cumail.in',
    phone: '9988862100',
    department: 'Computer Science & Engineering',
    designation: 'Deputy HOD (3rd Yr) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '304 A',
    cabinNumber: 'Cabin 304 A',
    subjects: ['Computer Science', 'Software Engineering'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-8745',
    userId: '',
    name: 'Er. Amrita Chaudhary',
    empId: '8745',
    email: 'amrita.e8745@cumail.in',
    phone: '7404373739',
    department: 'Computer Science & Engineering',
    designation: 'AO (Administrative Officer) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '312',
    cabinNumber: 'Cabin 312',
    subjects: ['Computer Science'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-11120',
    userId: '',
    name: 'Dr. Santosh Kumar',
    empId: '11120',
    email: 'santosh.e11120@cumail.in',
    phone: '7988308521',
    department: 'Computer Science & Engineering',
    designation: 'AO (Administrative Officer) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '312',
    cabinNumber: 'Cabin 312',
    subjects: ['Data Science', 'Machine Learning'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-11083',
    userId: '',
    name: 'Er. Aparna',
    empId: '11083',
    email: 'aparna.e11083@cumail.in',
    phone: '9467168136',
    department: 'Computer Science & Engineering',
    designation: 'AO (Administrative Officer) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '301',
    cabinNumber: 'Cabin 301',
    subjects: ['Computer Science'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-12832',
    userId: '',
    name: 'Er. Prashant Ahlawat',
    empId: '12832',
    email: 'prashant.e12832@cumail.in',
    phone: '9711014323',
    department: 'Computer Science & Engineering',
    designation: 'AO (Administrative Officer) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '312',
    cabinNumber: 'Cabin 312',
    subjects: ['Computer Networks', 'Operating Systems'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-12999',
    userId: '',
    name: 'Er. Kirat Kaur',
    empId: '12999',
    email: 'kirat.e12999@cumail.in',
    phone: '8968768698',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Assistant Professor',
    blockName: 'Chandigarh University Block B4',
    blockNumber: 'Block B4',
    roomNumber: '916',
    cabinNumber: 'Cabin 916',
    subjects: ['Java Programming', 'Data Structures'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-17528',
    userId: '',
    name: 'Dr. Priti',
    empId: '17528',
    email: 'priti.e17528@cumail.in',
    phone: '8699139773',
    department: 'Computer Science & Engineering',
    designation: 'Professor',
    blockName: 'Chandigarh University Block B4',
    blockNumber: 'Block B4',
    roomNumber: '915',
    cabinNumber: 'Cabin 915',
    subjects: ['Algorithms', 'Theory of Computation'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-16482',
    userId: '',
    name: 'Er. Natali Singla',
    empId: '16482',
    email: 'natali.e16482@cumail.in',
    phone: '9646986539',
    department: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    blockName: 'Chandigarh University Block B4',
    blockNumber: 'Block B4',
    roomNumber: '915',
    cabinNumber: 'Cabin 915',
    subjects: ['Database Systems', 'SQL'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-12830',
    userId: '',
    name: 'Dr. Neha Dutta',
    empId: '12830',
    email: 'neha.e12830@cumail.in',
    phone: '9996015285',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Associate Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '407',
    cabinNumber: 'Cabin 407',
    subjects: ['Artificial Intelligence', 'Machine Learning'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-5922',
    userId: '',
    name: 'Dr. Charnpreet Kaur',
    empId: '5922',
    email: 'charnpreet.cse@cumail.in',
    phone: '9780040116',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '309',
    cabinNumber: 'Cabin 309',
    subjects: ['Deep Learning', 'Python'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-10446',
    userId: '',
    name: 'Er. Deepika Sood',
    empId: '10446',
    email: 'deepika.e10446@cumail.in',
    phone: '9878976445',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Technical Trainer',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '611',
    cabinNumber: 'Cabin 611',
    subjects: ['Web Technologies', 'Full Stack Development'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-13572',
    userId: '',
    name: 'Er. Renuka Rattan',
    empId: '13572',
    email: 'renuka.e13572@cumail.in',
    phone: '7876777433',
    department: 'Computer Science & Engineering',
    designation: 'Assistant Professor / MSC',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '513',
    cabinNumber: 'Cabin 513',
    subjects: ['Cloud Computing', 'Cyber Security'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-11313',
    userId: '',
    name: 'Er. Pooja',
    empId: '11313',
    email: 'pooja.e11313@cumail.in',
    phone: '9405400002',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '302',
    cabinNumber: 'Cabin 302',
    subjects: ['Computer Programming', 'C++'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-18521',
    userId: '',
    name: 'Er. Shriya Dogra',
    empId: '18521',
    email: 'shriya.e18521@cumail.in',
    phone: '8350982816',
    department: 'Computer Science & Engineering',
    designation: 'Time Table Coordinator / Assistant Professor',
    blockName: 'Chandigarh University Block B4',
    blockNumber: 'Block B4',
    roomNumber: '908',
    cabinNumber: 'Cabin 908',
    subjects: ['Data Structures', 'C Programming'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-15545',
    userId: '',
    name: 'Er. Babita Sharma',
    empId: '15545',
    email: 'babita.e15545@cumail.in',
    phone: '9805034697',
    department: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '602',
    cabinNumber: 'Cabin 602',
    subjects: ['Software Architecture', 'Agile Methodologies'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-5026',
    userId: '',
    name: 'Er. Prashant',
    empId: '5026',
    email: 'prashant.cse@cumail.in',
    phone: '9416463293',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Assistant Professor',
    blockName: 'Chandigarh University Block B3',
    blockNumber: 'Block B3',
    roomNumber: '503',
    cabinNumber: 'Cabin 503',
    subjects: ['Discrete Mathematics', 'Theory of Computation'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    verified: true,
  },
  {
    id: 'cu-12255',
    userId: '',
    name: 'Er. Gurleen Kaur',
    empId: '12255',
    email: 'gurleen.e12255@cumail.in',
    phone: '9888443015',
    department: 'Computer Science & Engineering',
    designation: 'ACO (Academic Coordinator) / Assistant Professor',
    blockName: 'Chandigarh University Block B4',
    blockNumber: 'Block B4',
    roomNumber: '916',
    cabinNumber: 'Cabin 916',
    subjects: ['Operating Systems', 'System Programming'],
    status: 'available',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    verified: true,
  }
];
